version: '3.8'

services:
  go-app:
    build:
      context: ./go-app
    ports:
      - '8085:8085'
    volumes:
      - app_logs:/var/log/go-app

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./configs/otel-collector/config.yaml:/etc/otel/config.yaml
      - app_logs:/var/log/go-app:ro # Read-only mount of log files
    command: ['--config=/etc/otel/config.yaml']
    ports:
      - '7317:7317' # Custom OTLP gRPC
      - '7318:7318' # Custom OTLP HTTP
    depends_on:
      - go-app
      - mimir
      - loki

  mimir:
    image: grafana/mimir:latest
    command: ['-config.file=/etc/mimir/config.yaml']
    volumes:
      - ./configs/mimir/mimir-config.yaml:/etc/mimir/config.yaml
      - mimir-data:/data
    ports:
      - '9009:9009' # HTTP API and UI

  loki:
    image: grafana/loki:latest
    volumes:
      - ./configs/loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    # Use root user for now to avoid permission issues
    user: '0:0'

  grafana:
    image: grafana/grafana:9.5.1
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_FEATURE_TOGGLES_ENABLE=exploreMixedDatasources
      - GF_EXPLORE_ENABLED=true
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - ./configs/grafana/custom.ini:/etc/grafana/custom.ini
    depends_on:
      - mimir
      - loki

  tempo:
    image: grafana/tempo:latest
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./configs/tempo/config.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - '9411:9411'
      - '9412:9412'
      - '3200:3200'
    depends_on:
      - otel-collector

volumes:
  app_logs:
  mimir-data:
  loki-data:
  tempo-data:
