receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'go-app'
          scrape_interval: 5s  # More frequent scraping
          static_configs:
            - targets: ['go-app:8085']

processors:
  batch:
    send_batch_size: 10000
    timeout: 5s

exporters:
  prometheusremotewrite:
    endpoint: "http://mimir:9009/api/v1/push"
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]
  telemetry:
    logs:
      level: "debug"
