receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:7317
      http:
        endpoint: 0.0.0.0:7318

processors:
  batch:
    send_batch_size: 10000
    timeout: 5s

exporters:
  prometheusremotewrite:
    endpoint: "http://mimir:9009/api/v1/push"
    tls:
      insecure: true
    namespace: "demo"
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]
  telemetry:
    logs:
      level: "debug"
    metrics:
      level: "detailed"
