receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:7317
      http:
        endpoint: 0.0.0.0:7318

processors:
  batch:
    send_batch_size: 10000
    timeout: 5s

exporters:
  prometheusremotewrite:
    endpoint: "http://mimir:9009/api/v1/push"
    tls:
      insecure: true
    namespace: "demo"
  debug:
    verbosity: detailed
  otlp/tempo:
    endpoint: "tempo:9411"  # Changed from 4317 to 9411
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, debug]
  telemetry:
    logs:
      level: "debug"
    metrics:
      level: "detailed"
